repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black .
        language: python
        types: [python]
        require_serial: true
    -   id: pyright
        name: pyright 
        entry: pyright 
        language: python
        types: [python]
        require_serial: true
    -   id: ruff 
        name: ruff 
        entry: ruff check --fix
        language: python
        types: [python]
        require_serial: true
